name: Bandit
on:
  push:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'
  pull_request:
    paths:
      - '**.py'
    branches: 
      - main
      - 'ver_*'

jobs:
  bandit-analyze:
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        util/install-dependencies.sh
    - name: Analyze package with bandit
      run: |
        util/bandit.sh

