# This workflow will upload a Python Package via the Trusted Publishing functionality in PyPI.
name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Build package with Poetry
      run: |
        poetry build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

